---
#--------------------------------------------------------------------
# Each cluster provisioned must have an entry in the 
# vault['clusters'] dictionary.  The name used for the cluster
# MUST match all other references (i.e. that found in the site specific
# file under playbooks/vars and in 
# playbooks/inventory/group_vars/all/clusters.yml)
#
# This file is can be encrypted using ansible's vault encryption
# and when running the playbook you specific 'ask password' on the CLI
# so that Ansible can decrypt the file.
#
# Replace <CLUSTER_NAME> with a valid cluster name that matches
# the entry in clusters.yml.  There must be one entry for every
# cluster to be referenced
#--------------------------------------------------------------------
vault:
  clusters:
    <CLUSTER_NAME>:
      username:      'admin'
      password:      'Netapp123@'

         