---

-  name: "Assign disks to node"
   na_ontap_disks:
      hostname:         "{{ clusters[loop_arg['hostname']]['mgmt_ip'] }}"
      username:         "{{ clusters[loop_arg['hostname']]['username'] }}"
      password:         "{{ clusters[loop_arg['hostname']]['password'] }}"
      
      https:            true
      validate_certs:   false

      node:             "{{ loop_arg['node'] }}"

      disk_count:       "{{ loop_arg['disk_count']      | default(omit) }}"

   loop:    "{{ args }}"
   loop_control:
      loop_var:   loop_arg
   register:      role_result

