---

##############################################################################################################
#  This Role function is to add NetApp object default values if not specified from passed extra_vars
#  If key/value is defined in extra_vars, set_defaults role will NOT override values
##############################################################################################################

- name: 'Initialize temporary list for building combined default payload'
  set_fact:
    temp: []

- name:  'Combine defaults to passed extra_vars payload'
  set_fact:
    temp:   "{{ temp + [ services[service][operation]['defaults'][res_type] | combine( resources[idx] ) ]  }}"
  loop:    "{{ resources }}"
  loop_control:
    loop_var:   loop_resource
    index_var:  idx

- name: 'Merge combined defaults to global_completed_request'
  set_fact:
    global_completed_request:  "{{ global_completed_request | combine( { res_type: temp } ) }}"


  